import Head from "next/head";
import ContentContainer from "../../components/ui/content-container/content-container";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useRouter } from "next/router";
import { useTranslation } from "react-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./package-details.module.less";
import MyButton from "../../components/ui/my-button";
import { kuposModalErrorSuccessState } from "../../recoil/atoms/common";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { currentEventState } from "../../recoil/atoms/home";

const PackageDetails = () => {
  const router = useRouter();
  const { t } = useTranslation("common");

  //recoil states
  const setModalErrorSuccessState = useSetRecoilState(
    kuposModalErrorSuccessState
  );

  const currentEvent = useRecoilValue(currentEventState)


  console.log({ currentEvent })

  const buyNow = () => {
    // setModalErrorSuccessState({
    //   showModal: true,
    //   success: true,
    //   modalTitle: "Successfully Booked!",
    // });

    router.push("/checkout")
  };
  return (
    <>
      <MainWrapper t={t}>
        <div className={"container"}>
          <Head>
            <title>TRAVEL-PLANNER</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
              rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossOrigin="anonymous"
            />
          </Head>
        </div>

        <ContentContainer>
          <div className={classes.package}>
            <div className={classes.img_container}>
              <img src="/images/iustimages/image3.jpg" alt="package" />
            </div>

            <div className={classes.package_details}>
              <div className={classes.name}>{currentEvent?.title}</div>
              <div className={classes.desc}>KASHMIR :HEAVEN ON EARTH</div>

              <div className={classes.details_item}>
                <span className={classes.label}>Stay Period:</span> {currentEvent?.duration}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>Place of Visit:</span>{currentEvent?.place}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>Number of Persons:</span>{currentEvent?.persons || 3}
                Persons
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>Vehicle Type:</span>{currentEvent?.cab}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>Guide:</span>{currentEvent?.guide || "Sanes Trev"}
              </div>

              <div className={classes.details_item}>
                <span className={classes.hotel}>Hotel:</span>{currentEvent?.guide || "Vivanta Taj"}
              </div>
              <div className={classes.price}>
                <span className={classes.label}>Package Price:</span>{currentEvent?.total_price || "30000"}
              </div>

              <div className={classes.btn_container}>
                <MyButton label="Buy Now" onClick={buyNow} />
              </div>
            </div>
          </div>
        </ContentContainer>
      </MainWrapper>
    </>
  );
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "es", ["common"])),
  },
});

export default PackageDetails;
