import React from "react";
import classes from "./hotels.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
const Hotels = (props) => {
  const { t } = useTranslation("common");
  const hotelgallery = [
    {
      id: 0,
      image: <img src="/images/iustimages/h1.webp" />,
      desc: "Great place. staff was extra helpful. wifi was down in the whole area. person at the reception would put hot spot",
    },
    {
      id: 1,
      image: <img src="/images/iustimages/h2.webp" />,
      desc: "Hotel is clean, staff is well behaved but hotel is slightly away from the market and there is a really steep slope",
    },
    {
      id: 2,
      image: <img src="/images/iustimages/h3.jpg" />,
      desc: "Located right across a field of lush meadows is Vintage — a modern hotel with generous-sized rooms and all amenities",
    },
    {
      id: 3,
      image: <img src="/images/iustimages/h4.jpg" />,
      desc: "There are very few best hotels in Srinagar, Lalit is one of them. It is a bit far from the local markets ",
    },
    {
      id: 4,
      image: <img src="/images/iustimages/h5.webp" />,
      desc: "The Khyber Himalayan Resort & Spa is a top notch 5 star hotel located very close to the major attractions",
    },
    {
      id: 5,
      image: <img src="/images/iustimages/h6.webp" />,
      desc: "Staying on the Mascot Houseboat was a most enriching experience. The location by the quiet ",
    },
    {
      id: 6,
      image: <img src="/images/iustimages/h7.jpg" />,
      desc: "There are very few best hotels in Srinagar, Lalit is one of them. It is a bit far from the local markets",
    },
    {
      id: 7,
      image: <img src="/images/iustimages/h8.jpg" />,
      desc: "Lonely guest house was wonderful from the beginning to the end of our stay. We stayed for three nights ",
    },
    {
      id: 8,
      image: <img src="/images/iustimages/h9.jpg" />,
      desc: "This is the best hotel of my trip in India, the staff (Umar) is very friendly. He even waiting for me",
    },
    {
      id: 9,
      image: <img src="/images/iustimages/h10.jpg" />,
      desc: " I was horrific since im solo traveller . Then i was in hard time to reschedule my budget and look over",
    },
    {
      id: 10,
      image: <img src="/images/iustimages/h11.webp" />,
      desc: " This hostel is great value for money and the atmosphere is very welcoming and familiar.it was very attractive",
    },
  ];
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <>
          <EventHeading label="Hotels" />
          <div className={classes.hotels_main_container}>
            {hotelgallery.map((hotels) => {
              return (
                <div className={classes.hotels_section}>
                  <div className={classes.hotel_images}>
                    <div className={classes.hotels_image}>{hotels.image}</div>
                    <div className={classes.hotels_desc}>{hotels.desc}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      </div>
    </MainWrapper>
  );
};
export default Hotels;
