import React, { useEffect, useState } from "react";
import classes from "./hotels.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
import ContentContainer from "../../components/ui/content-container/content-container";
import { GetHotels } from "../../services/apis/apisHome";
import baseUrls from "../../services/constants/baseUrls";
const Hotels = (props) => {
  const { t } = useTranslation("common");

  const getHotelsFunc = GetHotels();
  const [hotels, setHotels] = useState([]);

  useEffect(() => {
    getHotelsFunc({
      callback: (res) => {
        console.log({ res });

        if (res?.data?.data) {
          // setHotels(res.data.data);
          let hotelsLocal = [];
          res?.data?.data?.map((hotel) => {
            hotelsLocal.push({
              ...hotel,
              image:
                baseUrls.baseUrl + "/" + res.mediaPath + "/" + hotel.reg_doc,
            });
          });
          setHotels(hotelsLocal);
        }
      },
    });
  }, []);

  console.log({ hotels });
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Hotels" />
          <div className={classes.hotels_main_container}>
            {hotels?.map((hotel) => {
              return (
                <div className={classes.hotels_section}>
                  <div className={classes.hotel_images}>
                    <div className={classes.hotels_image}>
                      <img src={hotel.image} />
                    </div>
                    <div className={classes.hotels_desc}>{hotel.name}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Hotels;
