import React from "react";
import classes from "./cabs.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
const Cabs = (props) => {
  const { t } = useTranslation("common");
  const cabgallery = [
    { id: 0, image: <img src="/images/iustimages/cab0.jpg" />, desc: "Innova" },
    {
      id: 1,
      image: <img src="/images/iustimages/cab1.jpeg" />,
      desc: "Toyota",
    },
    { id: 2, image: <img src="/images/iustimages/cab2.jpeg" />, desc: "Swift" },
    {
      id: 3,
      image: <img src="/images/iustimages/cab3.jpeg" />,
      desc: "Scorpio",
    },
    { id: 4, image: <img src="/images/iustimages/cab6.jpeg" />, desc: "Xylo" },
    {
      id: 5,
      image: <img src="/images/iustimages/cab5.jpeg" />,
      desc: "Vitara Brezza",
    },
    {
      id: 6,
      image: <img src="/images/iustimages/cab6.jpeg" />,
      desc: "Tavera",
    },
    { id: 7, image: <img src="/images/iustimages/cabb.png" />, desc: "Sumo" },
    {
      id: 8,
      image: <img src="/images/iustimages/cab8.jpg" />,
      desc: "Range Rover",
    },
    {
      id: 9,
      image: <img src="/images/iustimages/cab9.jpeg" />,
      desc: "SWift Dzire",
    },
  ];
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <>
          <EventHeading label="Cabs Section" />
          <div className={classes.cabs_main_container}>
            {cabgallery.map((cab) => {
              return (
                <div className={classes.cabs_section}>
                  <div className={classes.cab_images}>
                    <div className={classes.cabs_image}>{cab.image}</div>'
                    <div className={classes.cab_desc}>{cab.desc}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      </div>
    </MainWrapper>
  );
};
export default Cabs;
