import React from "react";
import classes from "./travelguide.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
const travelguide = (props) => {
  const { t } = useTranslation("common");
  const travelguidegallery = [
    {
      id: 0,
      image: <img src="/images/iustimages/tr1.jpg" />,
      desc: "Eveywhereist wanderer.",
    },
    {
      id: 1,
      image: <img src="/images/iustimages/tr2.jpeg" />,
      desc: "Sane traveller.",
    },
    {
      id: 2,
      image: <img src="/images/iustimages/tr3.webp" />,
      desc: "Travelling aqua.",
    },
    {
      id: 3,
      image: <img src="/images/iustimages/tr4.jpg" />,
      desc: "Travelwoman.",
    },
    {
      id: 4,
      image: <img src="/images/iustimages/tr5.jpeg" />,
      desc: "Travelman",
    },
    {
      id: 5,
      image: <img src="/images/iustimages/tr6.jpg" />,
      desc: "Exploring every city.",
    },
    {
      id: 6,
      image: <img src="/images/iustimages/tr7.jpg" />,
      desc: "Farther i can reach.",
    },
    {
      id: 7,
      image: <img src="/images/iustimages/tr8.jpg" />,
      desc: "Voyage Ventures",
    },
    {
      id: 8,
      image: <img src="/images/iustimages/tr9.jpg" />,
      desc: "Travel Trekkers",
    },
    {
      id: 9,
      image: <img src="/images/iustimages/tr10.jpeg" />,
      desc: "Devoted traveller.",
    },
    {
      id: 10,
      image: <img src="/images/iustimages/tr11.webp" />,
      desc: "Wanderlust Wonders.",
    },
    {
      id: 11,
      image: <img src="/images/iustimages/tr12.jpg" />,
      desc: "Pathway Pioneers.",
    },
  ];
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <>
          <EventHeading label="Guide Section" />
          <div className={classes.travelguide_main_container}>
            {travelguidegallery.map((travelguide) => {
              return (
                <div className={classes.travelguide_section}>
                  <div className={classes.travelguide_images}>
                    <div className={classes.travelguide_image}>
                      {travelguide.image}
                    </div>

                    <div className={classes.travelguide_desc}>
                      {travelguide.desc}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      </div>
    </MainWrapper>
  );
};
export default travelguide;
