import React, { useEffect, useState } from "react";
import classes from "./Travelguide.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
import ContentContainer from "../../components/ui/content-container/content-container";
import { GetGuides } from "../../services/apis/apisHome";
import baseUrls from "../../services/constants/baseUrls";
const Guides = (props) => {
  const { t } = useTranslation("common");

  const [guides, setGuides] = useState([]);

  const GetGuideFunc = GetGuides();

  useEffect(() => {
    GetGuideFunc({
      callback: (res) => {
        console.log("Response from guides api is..", res);

        let guidesLocal = [];
        if (res?.data?.data) {
          res?.data?.data?.map((guide) => {
            guidesLocal.push({
              ...guide,
              image:
                baseUrls.baseUrl +
                "/" +
                res.mediaPath +
                "/" +
                guide.profile_pic,
            });
          });
          setGuides(guidesLocal);
        }
      },
    });
  }, []);

  console.log({ guides });
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Guide Section" />
          <div className={classes.travelguide_main_container}>
            {guides.map((guide) => {
              return (
                <div className={classes.travelguide_section}>
                  <div className={classes.travelguide_images}>
                    <div className={classes.travelguide_image}>
                      <img src={guide.image} />
                    </div>

                    <div className={classes.travelguide_desc}>
                      {guide.details}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Guides;
