import React, { useState } from "react";
import ContentContainer from "../../components/ui/content-container/content-container";
import classes from "./profile.module.less";
import { useTranslation } from "react-i18next";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import Head from "next/head";
import Header from "../../components/ui/header";
import EventHeading from "../../components/headings";
import Tabs from "../../components/ui/tabs/tabs";
import EventsGallery from "../../components/Events-gallery";
import PackageDetails from "../package-details";
const Profile = () => {
  const { t } = useTranslation("common");
  const [selectedTab, setSelectedTab] = useState(0);

  const tabs = ["Kashmir", "Outside"];
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Profile" />
          <div className={classes.profile_details}>
            <div className={classes.profile}>
              <img src="/images/iustimages/as.jpg" />
            </div>
            <div className={classes.profile_body}>
              <div className={classes.details_item}>
                <span className={classes.label}>NAME : </span>Aasif Gani{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>ADDRESS : </span> Tiken batpora{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>CITY : </span> Pulwama{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>CONTACT NO : </span> 7889989660{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>EMAIL : </span>{" "}
                mohammadaasif911@gmail.com{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>DESTINATION:</span>Gulmarg
              </div>
            </div>
          </div>
          <div className={classes.tabs_container}>
            <Tabs data={tabs} setTab={setSelectedTab} />
            {selectedTab === 0 ? (
              <img
                src={"/images/iustimages/cabb.png"}
                style={{ width: "50", border_radius: "20" }}
              />
            ) : (
              "outside packages"
            )}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Profile;
