import React, { useState } from "react";
import ContentContainer from "../../components/ui/content-container/content-container";
import classes from "./profile.module.less";
import { useTranslation } from "react-i18next";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import Head from "next/head";
import EventHeading from "../../components/headings";
import Tabs from "../../components/ui/tabs/tabs";
import DateService from "../../services/dateService";
const Profile = () => {
  const { t } = useTranslation("common");
  const [selectedTab, setSelectedTab] = useState(0);

  const tabs = ["Upcoming Bookings", "Past Bookings"];


  const [bookings, setBookings] = useState([
    { id: 0, title: "3 days 2 nights", Location: "Gulmarg", date: "03/09/2023", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
    { id: 1, title: "3 days 2 nights", Location: "Gulmarg", date: "03/07/2023", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
    { id: 2, title: "3 days 2 nights", Location: "Gulmarg", date: "03/08/2023", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
    { id: 3, title: "3 days 2 nights", Location: "Gulmarg", date: "03/10/2023", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
    { id: 4, title: "3 days 2 nights", Location: "Gulmarg", date: "03/11/2023", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
    { id: 5, title: "3 days 2 nights", Location: "Gulmarg", date: "03/01/2024", vehicle: "Taveera", guide: "Dave", passengers: "5", hotel: "Shahi Mehal" },
  ])

  const currentDate = new Date().getTime();




  const renderBooking = booking => {
    return (
      <div className="booking">
        <div className="title">{booking.title}</div>
        <div>
          <span>{booking.date}</span>
          <span>{booking.location}</span>
          <span>{booking.guide}</span>
          <span>{booking.vehicle}</span>
          <span>{booking.hotel}</span>
        </div>
      </div>
    )
  }


  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Profile" />
          <div className={classes.profile_details}>
            <div className={classes.profile}>
              <img src="/images/iustimages/as.jpg" />
            </div>
            <div className={classes.profile_body}>
              <div className={classes.details_item}>
                <span className={classes.label}>NAME : </span>Aasif Gani{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>ADDRESS : </span> Tiken batpora{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>CITY : </span> Pulwama{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>CONTACT NO : </span> 7889989660{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>EMAIL : </span>{" "}
                mohammadaasif911@gmail.com{" "}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>DESTINATION:</span>Gulmarg
              </div>
            </div>
          </div>
          <div className={classes.tabs_container}>
            <Tabs data={tabs} setTab={setSelectedTab} />
            {selectedTab === 0 ?

              <div>
                {bookings?.map(booking => {

                  let bookingdate = new Date(DateService.changeDateFormat(booking.date, "dd/mm/yyyy", "yyyy-mm-dd"))


                  if (bookingdate > currentDate) {
                    return renderBooking(booking)
                  }
                })}
              </div>

              : (
                <div>
                  {bookings?.map(booking => {

                    let bookingdate = new Date(DateService.changeDateFormat(booking.date, "dd/mm/yyyy", "yyyy-mm-dd"))


                    if (bookingdate < currentDate) {
                      return renderBooking(booking)
                    }
                  })}
                </div>
              )}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Profile;
