import React, { useEffect, useState } from "react";
import ContentContainer from "../../components/ui/content-container/content-container";
import classes from "./profile.module.less";
import { useTranslation } from "react-i18next";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import Head from "next/head";
import EventHeading from "../../components/headings";
import Tabs from "../../components/ui/tabs/tabs";
import DateService from "../../services/dateService";
import { MyBookings } from "../../services/apis/apisHome";
import { useRecoilValue } from "recoil";
import { loginDataState } from "../../recoil/atoms/common";
import CommonService from "../../services/commonService";
const Profile = () => {
  const { t } = useTranslation("common");
  const [selectedTab, setSelectedTab] = useState(0);

  //apis
  const getMyBookings = MyBookings();

  // recoil states
  const [loginData, setLoginData] = useState(null);

  const tabs = ["Upcoming Bookings", "Past Bookings"];

  const [bookings, setBookings] = useState([]);

  const currentDate = new Date().toDateString();

  useEffect(() => {
    let logindata = CommonService.getLocalEncryp("loginData");

    console.log({ logindata });

    if (logindata) {
      setLoginData(loginData);
      getMyBookings({
        callback: (res) => {
          if (res?.data) {
            setBookings(res.data);
          }
        },

        data: { user_id: logindata?.id },
      });
    }
  }, []);

  console.log({ bookings });

  const renderBooking = (booking) => {
    return (
      <div className={classes.booking}>
        <div className={classes.title}>{booking.title}</div>
        <div className={classes.booking_details}>
          <span className={classes.title_details}>
            {booking?.package?.name}
          </span>
          <span className={classes.title_details}>
            {booking?.package?.pacakage_details}
          </span>
          <span className={classes.title_details}>
            <span className={classes.label}>Date : </span>
            {booking.booking_date.split(" ")[0]}
          </span>
          <span className={classes.title_details}>
            <span className={classes.label}>Total Amount : </span>
            {booking.amount}
          </span>
          {/* <span className={classes.title_details}>
            <span className={classes.label}>Location : </span>
            {booking.Location}
          </span> */}
          {/* <span className={classes.title_details}>
            <span className={classes.label}>Guide name : </span>
            {booking.guide}
          </span>
          <span className={classes.title_details}>
            <span className={classes.label}>Cab : </span>
            {booking.vehicle}
          </span>
          <span className={classes.title_details}>
            <span className={classes.label}>Hotel : </span>
            {booking.hotel}
          </span> */}
        </div>
      </div>
    );
  };

  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Profile" />
          <div className={classes.profile_details}>
            <div className={classes.profile}>
              <img src="/images/iustimages/as.jpg" />
            </div>
            <div className={classes.profile_body}>
              <div className={classes.details_item}>
                <span className={classes.label}>NAME : </span>
                {loginData?.name}
              </div>
              {/* <div className={classes.details_item}>
                <span className={classes.label}>ADDRESS : </span> Tiken batpora{" "}
              </div> */}
              {/* <div className={classes.details_item}>
                <span className={classes.label}>CITY : </span> Pulwama{" "}
              </div> */}
              <div className={classes.details_item}>
                <span className={classes.label}>CONTACT NO : </span>
                {loginData?.phone}
              </div>
              <div className={classes.details_item}>
                <span className={classes.label}>EMAIL : </span>
                {loginData?.email}
              </div>
              {/* <div className={classes.details_item}>
                <span className={classes.label}>DESTINATION:</span>Gulmarg
              </div> */}
            </div>
          </div>
          <div className={classes.tabs_container}>
            <Tabs data={tabs} setTab={setSelectedTab} />
            {selectedTab === 0 ? (
              <div className={classes.booking_container}>
                {bookings &&
                  bookings.length &&
                  bookings?.map((booking) => {
                    let bookingdate = new Date(
                      // DateService.changeDateFormat(
                      booking.booking_date.split(" ")[0]
                      // "dd/mm/yyyy",
                      // "yyyy-mm-dd"
                      // )
                    ).toDateString();

                    console.log({ bookingdate });
                    console.log({ currentDate });

                    if (bookingdate >= currentDate) {
                      return renderBooking(booking);
                    }
                  })}
              </div>
            ) : (
              <div className={classes.booking_container}>
                {bookings?.map((booking) => {
                  let bookingdate = new Date(
                    DateService.changeDateFormat(
                      booking.date,
                      "dd/mm/yyyy",
                      "yyyy-mm-dd"
                    )
                  );

                  if (bookingdate < currentDate) {
                    return renderBooking(booking);
                  }
                })}
              </div>
            )}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Profile;
