import React, { useEffect, useState } from "react";
import classes from "./drivers.module.less";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "react-i18next";
import Head from "next/head";
import { cartListState } from "../../recoil/atoms/cart";
import EventHeading from "../../components/headings";
import ContentContainer from "../../components/ui/content-container/content-container";
import { GetDrivers } from "../../services/apis/apisHome";
import baseUrls from "../../services/constants/baseUrls";
import { faDriversLicense } from "@fortawesome/free-solid-svg-icons";
const Drivers = (props) => {
  const { t } = useTranslation("common");

  const [drivers, setDrivers] = useState([]);

  const GetDriverFunc = GetDrivers();

  useEffect(() => {
    GetDriverFunc({
      callback: (res) => {
        console.log("Response from drivers api is..", res);

        let driversLocal = [];
        if (res?.data?.data) {
          res?.data?.data?.map((driver) => {
            driversLocal.push({
              ...driver,
              image:
                baseUrls.baseUrl +
                "/" +
                res.mediaPath +
                "/" +
                driver.profile_pic,
            });
          });
          setDrivers(driversLocal);
        }
      },
    });
  }, []);

  console.log({ drivers });
  return (
    <MainWrapper t={t}>
      <div className={classes.container}>
        <Head>
          <title>TRAVEL-PLANNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossOrigin="anonymous"
          />
        </Head>
        <ContentContainer>
          <EventHeading label="Driver_Section" />
          <div className={classes.driver_section_main_container}>
            {drivers.map((driver) => {
              return (
                <div className={classes.driver_section}>
                  <div className={classes.driver_images}>
                    <div className={classes.driver_image}>
                      <img src={driver.image} />
                    </div>

                    <div className={classes.driver_desc}>{driver.details}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </ContentContainer>
      </div>
    </MainWrapper>
  );
};
export default Drivers;
