import { useTranslation } from "react-i18next";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import ContentContainer from "../../components/ui/content-container/content-container";
import Head from "next/head";

const Terms = () => {
  const { t } = useTranslation("common");
  return (
    <MainWrapper t={t}>
      <Head>
        <title>TRAVEL-PLANNER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        />
      </Head>
      <ContentContainer>
        Terms and conditions
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
        <div>1. point 1</div>
      </ContentContainer>
    </MainWrapper>
  );
};

export default Terms;
